variables:
  PROJ_NAME: 'wicc-bet-webui'
  TAR_FILE: 'wicc-bet-webui.tar.gz'
  ARTIFACTS_MASTER: '/tmp/artifacts/master'
  ARTIFACTS_PROD: '/tmp/artifacts/prod/wicc-game-webui'
  WEB_DIR: '/home/devops/www/game-webui'
  
cache:
  paths:
    - node_modules/
  
stages:
  - build

build for dev master:
  stage: build
  script:
    - whoami
    - mkdir -p $ARTIFACTS_MASTER
    - pwd
    - yarn install --network-timeout 1000000
    - yarn run build

    #- tar czvf $ARTIFACTS_PROD/$TAR_FILE ./dist/*
    - rsync -a --delete ./dist/ $WEB_DIR
  only: 
    - master
  tags:
    - wicc-dev